name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Clone NiseAPI
        run: |
          git clone https://github.com/Lodingglue/nise-api.git niseAPI
          

      - name: Clone MiniAPI
        run: |
          git clone https://github.com/NexCaise/Ambient-MiniAPI.git miniAPI

      - name: Configure and Build
        run: |
          xmake f -p android -a arm64-v8a --ndk=$ANDROID_NDK_HOME -m release -y
          xmake -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libForceCloseOreUI
          path: build/android/arm64-v8a/release
